### ISSUE TITLE
Update app

### ISSUE THREAD

**Issue by hirawatt** [streamlit/theming-showcase-blue#2]
Can I open a pull request with these updated in the app?
```[tasklist]
### Tasks
- [ ] Update : app to use latest streamlit version
- [ ] Fix : minor errors - showing 0 at the top when opening app
- [ ] Fix : Swtiching to custom theme link not working
```
![image](https://user-images.githubusercontent.com/38539637/226126376-b156e9f0-b25d-4b76-8a48-9f7344efbbd3.png)
![image](https://user-images.githubusercontent.com/38539637/226126414-e48a9469-42bc-4dcd-ac8d-f26e4ceb9de3.png)

Thank You
